export const environment = {
  production: true,
  baseUrl: 'https://app.opremiando.com/api',
  baseUrlPix: 'https://app.opremiando.com',
  baseUrlLogin: 'https://app.opremiando.com/login',
  baseUrlLoginExists: 'https://app.opremiando.com',
  baseUserServiceUrl: 'http://localhost',
  baseGeoServiceUrl: 'http://localhost',
  baseCustomerServiceUrl: 'http://localhost',
  baseCrmServiceUrl: 'http://localhost',
  gmailRedirectUrl: 'http://localhost',
  baseEmailServiceUrl: 'http://localhost',
  baseProductServiceUrl: 'http://localhost',
  /* baseUrl: 'http://localhost:8081/api',
  baseUrlPix: 'http://localhost:8081',
  baseUrlLogin: 'http://localhost:8081/login',
  baseUrlLoginExists: 'http://localhost:8081',
  baseUserServiceUrl: 'http://localhost',
  baseGeoServiceUrl: 'http://localhost',
  baseCustomerServiceUrl: 'http://localhost',
  baseCrmServiceUrl: 'http://localhost',
  gmailRedirectUrl: 'http://localhost',
  baseEmailServiceUrl: 'http://localhost',
  baseProductServiceUrl: 'http://localhost', */
};
